name: gpboost_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - nb_conda
  - pdpbox
  - pip:
      - mlflow
      - matplotlib
      - lightgbm
      - gpboost
      - numpy
      - pandas
      - optuna
      - hydra-core
      - hydra-optuna-sweeper
      - seaborn
      - scikit-learn
      - scipy
      - shap
      - ipykernel
