model:
  QUANT_PARAM: 0.75
  ROUNDS: 1000
  dir: 'outputs/optuna'
  optuna_seed: 43
  budget_time: 300
 
params:
    task': 'train'
    boosting_type': 'gbdt'
    objective': 'quantile'
    metric': 'quantile'
    num_leaves': 70
    max_depth': 8
    feature_fraction': 0.8
    bagging_fraction': 0.8
    bagging_freq': 5
    learning_rate': 0.01
    seed: 42
    num_threads: 8
 
mlflow:
    runname : 'first'
    exp_name: 'TEST_GPBOOST'
 